name: masamune_purchase_firebase
description: >-
  Plugin that extends the billing system plugin to the processing by the server (Firebase).
version: 0.6.1
homepage: https://mathru.net
repository: https://github.com/mathrunet/flutter_masamune_purchase_firebase

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # in app purchase
  http: ^0.12.2
  simple_rsa: ^0.0.5
  in_app_purchase: ^0.3.4
  # Masamune
  masamune_core: ^0.6.0
  masamune_flutter: ^0.6.0
  masamune_localize: ^0.6.0
  masamune_purchase: ^0.6.0
  masamune_firebase: ^0.6.0
  masamune_firebase_mobile: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Masamune
  masamune_test: ^0.5.0

# dependency_overrides:
#   masamune_core:
#     path: ../masamune_core/
#   masamune_localize:
#     path: ../masamune_localize/
#   masamune_flutter:
#     path: ../masamune_flutter/
#   masamune_purchase:
#     path: ../masamune_purchase/
#   masamune_firebase:
#     path: ../masamune_firebase/
#   masamune_firebase_mobile:
#     path: ../masamune_firebase_mobile/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
